# Anisble playbook to remove a package from a system
# Usage: ansible-playbook ansible-remove-package.yaml -e "package_name=<package_name>"
---
- hosts: all
  become: yes
  become_method: su
  become_user: root
  connection: ssh
  tasks:
    - name: Remove package
      package:
        name: "{{ package_name }}"
        state: absent


